export const SOCKET_INIT_SOCKET = 'SOCKET_INIT_SOCKET';

export const LOCALIZATION_INIT_I18N = 'LOCALIZATION_INIT_I18N';
export const LOCALIZATION_CHANGE_LANGUAGE = 'LOCALIZATION_CHANGE_LANGUAGE';

export const COMMON_TOGGLE_LOADING = 'COMMON_TOGGLE_LOADING';
export const COMMON_SHOW_NOTIFICATION = 'COMMON_SHOW_NOTIFICATION';

export const SETTINGS_CHANGE_SETTINGS = 'SETTINGS_CHANGE_SETTINGS';
export const REGISTER_BIOMETRIC = 'REGISTER_BIOMETRIC';

export const AUTHENTICATION_LOGIN_DOMAIN = 'AUTHENTICATION_LOGIN_DOMAIN';
export const GENERATE_NEW_KIS_CARD = 'GENERATE_NEW_KIS_CARD';
export const RESEND_LOGIN_OTP = 'RESEND_LOGIN_OTP';
export const AUTHENTICATION_LOGIN_BIOMETRIC = 'AUTHENTICATION_LOGIN_BIOMETRIC';
export const AUTHENTICATION_VERIFY_OTP = 'AUTHENTICATION_VERIFY_OTP';
export const AUTHENTICATION_VERIFY_OTP_BIOMETRIC = 'AUTHENTICATION_VERIFY_OTP_BIOMETRIC';
export const AUTHENTICATION_LOGIN_VIEW_MODE = 'AUTHENTICATION_LOGIN_VIEW_MODE';
export const AUTHENTICATION_SIGNOUT = 'AUTHENTICATION_SIGNOUT';
export const BIOMETRIC_VERIFICATION_FAILED_TRIGGER = 'BIOMETRIC_VERIFICATION_FAILED_TRIGGER';
export const BIOMETRIC_VERIFICATION_FAILED_TYPE = 'BIOMETRIC_VERIFICATION_FAILED_TYPE';
export const NOTIFICATION_MOBILE_OTP = 'NOTIFICATION_MOBILE_OTP';

export const QUERY_USING_BIOMETRIC_STATUS = 'QUERY_USING_BIOMETRIC_STATUS';

export const NOTIFICATION_ORDER_MATCH = 'NOTIFICATION_ORDER_MATCH';
export const NOTIFICATION_STOP_ORDER_ACTIVATION = 'NOTIFICATION_STOP_ORDER_ACTIVATION';
export const NOTIFICATION_ALARM_PRICE = 'NOTIFICATION_ALARM_PRICE';

export const AWS_GET_SIGNED_DATA = 'AWS_GET_SIGNED_DATA';
export const AWS_UPLOAD_IMAGE = 'AWS_UPLOAD_IMAGE';

export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';

export const MARKET_INIT = 'MARKET_INIT';
export const RELOAD_MARKET_DATA = 'RELOAD_MARKET_DATA';
export const MARKET_INIT_EXTRA = 'MARKET_INIT_EXTRA';
export const MARKET_SET_CURRENT_SYMBOL = 'MARKET_SET_CURRENT_SYMBOL';
export const MARKET_SET_CURRENT_INDEX = 'MARKET_SET_CURRENT_INDEX';
export const MARKET_SUBSCRIBE_SYMBOL = 'MARKET_SUBSCRIBE_SYMBOL';
export const MARKET_UNSUBSCRIBE_SYMBOL = 'MARKET_UNSUBSCRIBE_SYMBOL';
export const MARKET_SUBSCRIBE_CURRENT_SYMBOL = 'MARKET_SUBSCRIBE_CURRENT_SYMBOL';
export const MARKET_QUERY_SYMBOL_DATA = 'MARKET_QUERY_SYMBOL_DATA';
export const MARKET_GET_QUOTE_SYMBOL_DATA = 'MARKET_GET_QUOTE_SYMBOL_DATA';
export const MARKET_GET_MINUTE_SYMBOL_DATA = 'MARKET_GET_MINUTE_SYMBOL_DATA';
export const MARKET_GET_PERIOD_SYMBOL_DATA = 'MARKET_GET_PERIOD_SYMBOL_DATA';
export const MARKET_GET_TICK_SYMBOL_DATA = 'MARKET_GET_TICK_SYMBOL_DATA';
export const MARKET_GET_UP_DOWN_STOCK_RANKING = 'MARKET_GET_UP_DOWN_STOCK_RANKING';
export const MARKET_GET_FOREIGNER_SYMBOL_DATA = 'MARKET_GET_FOREIGNER_SYMBOL_DATA';

export const BUSINESS_INFO_QUERY_BUSINESS_INFO = 'BUSINESS_INFO_QUERY_BUSINESS_INFO';

export const SEARCH_ADD_SYMBOL = 'SEARCH_ADD_SYMBOL';
export const SEARCH_REMOVE_SYMBOL = 'SEARCH_REMOVE_SYMBOL';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';

export const FAVORITE_GET_FAVORITE_LISTS = 'FAVORITE_GET_FAVORITE_LISTS';
export const FAVORITE_CHANGE_FAVORITE_LIST = 'FAVORITE_CHANGE_FAVORITE_LIST';
export const FAVORITE_UPDATE_FAVORITE_LIST = 'FAVORITE_UPDATE_FAVORITE_LIST';
export const FAVORITE_UPDATE_FAVORITE_LIST_ORDER = 'FAVORITE_UPDATE_FAVORITE_LIST_ORDER';
export const FAVORITE_ADD_FAVORITE_LIST = 'FAVORITE_ADD_FAVORITE_LIST';
export const FAVORITE_GET_FAVORITE_LISTS_FAILED = 'FAVORITE_GET_FAVORITE_LISTS_FAILED';
export const FAVORITE_GET_FAVORITE_LISTS_RESET = 'FAVORITE_GET_FAVORITE_LISTS_RESET';
export const FAVORITE_GET_FAVORITE_LISTS_SUCCESS = 'FAVORITE_GET_FAVORITE_LISTS_SUCCESS';
export const FAVORITE_GET_FAVORITE_LISTS_LOADING = 'FAVORITE_GET_FAVORITE_LISTS_LOADING';
export const FAVORITE_DELETE_FAVORITE_LIST = 'FAVORITE_DELETE_FAVORITE_LIST';

export const ALARM_GET_ALARM_SETTINGS = 'ALARM_GET_ALARM_SETTINGS';
export const ALARM_ADD_ALARM_SETTING = 'ALARM_ADD_ALARM_SETTING';
export const ALARM_UPDATE_ALARM_SETTING = 'ALARM_UPDATE_ALARM_SETTING';
export const ALARM_DELETE_ALARM_SETTING = 'ALARM_DELETE_ALARM_SETTING';

export const NEWS_QUERY_SYMBOL_NEWS = 'NEWS_QUERY_SYMBOL_NEWS';
export const NEWS_QUERY_FAVORITE_NEWS = 'NEWS_QUERY_FAVORITE_NEWS';

export const ACCOUNT_CHANGE_ACCOUNT = 'ACCOUNT_CHANGE_ACCOUNT';
export const ACCOUNT_QUERY_ACCOUNT_BANKS = 'ACCOUNT_QUERY_ACCOUNT_BANKS';
export const ACCOUNT_QUERY_ACCOUNT_INFO = 'ACCOUNT_QUERY_ACCOUNT_INFO';
export const ACCOUNT_QUERY_ALL_ACCOUNTS = 'ACCOUNT_QUERY_ALL_ACCOUNTS';
export const ACCOUNT_CHANGE_ORDER_PASSWORD = 'ACCOUNT_CHANGE_ORDER_PASSWORD';
export const ACCOUNT_CHANGE_HTS_PASSWORD = 'ACCOUNT_CHANGE_HTS_PASSWORD';
export const ACCOUNT_QUERY_EQUITY_ACCOUNT_BALANCE = 'ACCOUNT_QUERY_EQUITY_ACCOUNT_BALANCE';
export const ACCOUNT_QUERY_STOCK_BALANCE = 'ACCOUNT_QUERY_STOCK_BALANCE';
export const ACCOUNT_QUERY_EQUITY_BUYABLE_INFO = 'ACCOUNT_QUERY_EQUITY_BUYABLE_INFO';
export const ACCOUNT_QUERY_EQUITY_SELLABLE_INFO = 'ACCOUNT_QUERY_EQUITY_SELLABLE_INFO';
export const ACCOUNT_QUERY_ACCOUNT_MOBILE = 'ACCOUNT_QUERY_ACCOUNT_MOBILE';
export const ACCOUNT_QUERY_EQUITY_CASH_BALANCE_DETAIL = 'ACCOUNT_QUERY_EQUITY_CASH_BALANCE_DETAIL';
export const ACCOUNT_QUERY_EQUITY_STOCK_BALANCE_DETAIL = 'ACCOUNT_QUERY_EQUITY_STOCK_BALANCE_DETAIL';
export const ACCOUNT_QUERY_EQUITY_ASSET_INFO_DETAIL = 'ACCOUNT_QUERY_EQUITY_ASSET_INFO_DETAIL';
export const ACCOUNT_QUERY_EQUITY_LOAN_HISTORY = 'ACCOUNT_QUERY_EQUITY_LOAN_HISTORY';
export const ACCOUNT_QUERY_TRANSACTION_STATEMENT = 'ACCOUNT_QUERY_TRANSACTION_STATEMENT';
export const QUERY_ACCOUNT_MARGIN = 'QUERY_ACCOUNT_MARGIN';

export const ORDER_QUERY_ORDER_HISTORY = 'ORDER_QUERY_ORDER_HISTORY';
export const ORDER_QUERY_ORDER_TODAY_UNMATCH = 'ORDER_QUERY_ORDER_TODAY_UNMATCH';
export const ORDER_QUERY_STOP_ORDER_HISTORY = 'ORDER_QUERY_STOP_ORDER_HISTORY';
export const ORDER_QUERY_ALL_STOP_ORDER_HISTORY = 'ORDER_QUERY_ALL_STOP_ORDER_HISTORY';
export const ORDER_QUERY_ADVANCE_ORDER_HISTORY = 'ORDER_QUERY_ADVANCE_ORDER_HISTORY';
export const ORDER_QUERY_SELLABLE_ODDLOT_STOCKS = 'ORDER_QUERY_SELLABLE_ODDLOT_STOCKS';
export const ORDER_QUERY_ODDLOT_ORDER_HISTORY = 'ORDER_QUERY_ODDLOT_ORDER_HISTORY';
export const ORDER_QUERY_ODDLOT_TODAY_UNMATCH = 'ORDER_QUERY_ODDLOT_TODAY_UNMATCH';
export const ORDER_PLACE_ORDER = 'ORDER_PLACE_ORDER';
export const ORDER_MODIFY_ORDER = 'ORDER_MODIFY_ORDER';
export const ORDER_CANCEL_ORDER = 'ORDER_CANCEL_ORDER';

export const WITHDRAW_MONEY_QUERY_BANK_ACCOUNTS = 'WITHDRAW_MONEY_QUERY_BANK_ACCOUNTS';
export const WITHDRAW_MONEY_QUERY_BANK_INFO = 'WITHDRAW_MONEY_QUERY_BANK_INFO';
export const WITHDRAW_MONEY_REQUEST = 'WITHDRAW_MONEY_REQUEST';
export const WITHDRAW_MONEY_QUERY_HISTORY = 'WITHDRAW_MONEY_QUERY_HISTORY';
export const WITHDRAW_MONEY_CANCEL_REQUEST = 'WITHDRAW_MONEY_CANCEL_REQUEST';

export const TRANSFER_CASH_QUERY_TRANSFER_ACCOUNT = 'TRANSFER_CASH_QUERY_TRANSFER_ACCOUNT';
export const TRANSFER_CASH_TRANSFER_REQUEST = 'TRANSFER_CASH_TRANSFER_REQUEST';
export const TRANSFER_CASH_TRANSFER_CANCEL_REQUEST = 'TRANSFER_CASH_TRANSFER_CANCEL_REQUEST';
export const TRANSFER_CASH_QUERY_TRANSACTION_HISTORY = 'TRANSFER_CASH_QUERY_TRANSACTION_HISTORY';

export const TRANSFER_STOCK_QUERY_AVAILABLE = 'TRANSFER_STOCK_QUERY_AVAILABLE';
export const TRANSFER_STOCK_QUERY_TRANSACTION_HISTORY = 'TRANSFER_STOCK_QUERY_TRANSACTION_HISTORY';
export const TRANSFER_STOCK_TRANSFER_REQUEST = 'TRANSFER_STOCK_TRANSFER_REQUEST';

export const SECURED_LOAN_QUERY_LOAN_BANKS = 'SECURED_LOAN_QUERY_LOAN_BANKS';
export const SECURED_LOAN_QUERY_AVAILABLE_LOANS = 'SECURED_LOAN_QUERY_AVAILABLE_LOANS';
export const SECURED_LOAN_QUERY_LOAN_DETAIL = 'SECURED_LOAN_QUERY_LOAN_DETAIL';
export const SECURED_LOAN_REGISTER = 'SECURED_LOAN_REGISTER';
export const SECURED_LOAN_QUERY_LOAN_HISTORY = 'SECURED_LOAN_QUERY_LOAN_HISTORY';

export const RIGHTS_SUBSCRIPTION_QUERY_AVAILABLE = 'RIGHTS_SUBSCRIPTION_QUERY_AVAILABLE';
export const RIGHTS_EXERCISE_REGISTRATION_QUERY = 'RIGHTS_EXERCISE_REGISTRATION_QUERY';
export const RIGHTS_SUBSCRIPTION_QUERY_DETAIL = 'RIGHTS_SUBSCRIPTION_QUERY_DETAIL';
export const RIGHTS_SUBSCRIPTION_REGISTER = 'RIGHTS_SUBSCRIPTION_REGISTER';

export const DERIVATIVES_ACCOUNT_QUERY_ACCOUNT_SUMMARY = 'DERIVATIVES_ACCOUNT_QUERY_ACCOUNT_SUMMARY';
export const DERIVATIVES_ACCOUNT_QUERY_ACCOUNT_EQUITY = 'DERIVATIVES_ACCOUNT_QUERY_ACCOUNT_EQUITY';
export const DERIVATIVES_ACCOUNT_QUERY_DAILY_BALANCE = 'DERIVATIVES_ACCOUNT_QUERY_DAILY_BALANCE';
export const DERIVATIVES_ACCOUNT_QUERY_RISK_RATIO = 'DERIVATIVES_ACCOUNT_QUERY_RISK_RATIO';
export const DERIVATIVES_ACCOUNT_QUERY_DAILY_PROFIT_LOSS = 'DERIVATIVES_ACCOUNT_QUERY_DAILY_PROFIT_LOSS';
export const DERIVATIVES_ACCOUNT_QUERY_CUMULATIVE_PROFIT_LOSS = 'DERIVATIVES_ACCOUNT_QUERY_CUMULATIVE_PROFIT_LOSS';
export const DERIVATIVES_ACCOUNT_QUERY_TODAY_OPEN_POSITION = 'DERIVATIVES_ACCOUNT_QUERY_TODAY_OPEN_POSITION';

export const DERIVATIVES_HISTORY_QUERY_MARGIN_CALL = 'DERIVATIVES_HISTORY_QUERY_MARGIN_CALL';
export const DERIVATIVES_HISTORY_QUERY_POSITION_HISTORY = 'DERIVATIVES_HISTORY_QUERY_POSITION_HISTORY';
export const DERIVATIVES_HISTORY_QUERY_SETTLEMENT_HISTORY = 'DERIVATIVES_HISTORY_QUERY_SETTLEMENT_HISTORY';

export const DERIVATIVES_ORDER_QUERY_ORDER_HISTORY = 'DERIVATIVES_ORDER_QUERY_ORDER_HISTORY';
export const DERIVATIVES_ORDER_QUERY_STOP_ORDER_HISTORY = 'DERIVATIVES_ORDER_QUERY_STOP_ORDER_HISTORY';
export const DERIVATIVES_ORDER_QUERY_ORDER_TODAY_UNMATCH = 'DERIVATIVES_ORDER_QUERY_ORDER_TODAY_UNMATCH';
export const DERIVATIVES_ORDER_QUERY_ADVANCE_ORDER_HISTORY = 'DERIVATIVES_ORDER_QUERY_ADVANCE_ORDER_HISTORY';
export const DERIVATIVES_ORDER_PLACE_ORDER = 'DERIVATIVES_ORDER_PLACE_ORDER';
export const DERIVATIVES_ORDER_CANCEL_ORDER = 'DERIVATIVES_ORDER_CANCEL_ORDER';
export const DERIVATIVES_ORDER_MODIFY_ORDER = 'DERIVATIVES_ORDER_MODIFY_ORDER';
export const DERIVATIVES_ORDER_QUERY_ORDER_AVAILABLE = 'DERIVATIVES_ORDER_QUERY_ORDER_AVAILABLE';

export const DERIVATIVES_TRANSFER_QUERY_WITHDRAW_INFO = 'DERIVATIVES_TRANSFER_QUERY_WITHDRAW_INFO';

export const DERIVATIVES_TRANSFER_QUERY_CASH_TRANSFER_INFO = 'DERIVATIVES_TRANSFER_QUERY_CASH_TRANSFER_INFO';

export const DERIVATIVES_TRANSFER_DEPOSIT_IM_REQUEST = 'DERIVATIVES_TRANSFER_DEPOSIT_IM_REQUEST';
export const DERIVATIVES_TRANSFER_QUERY_DEPOSIT_IM_INFO = 'DERIVATIVES_TRANSFER_QUERY_DEPOSIT_IM_INFO';
export const DERIVATIVES_TRANSFER_QUERY_TRANSFER_IM_BANK = 'DERIVATIVES_TRANSFER_QUERY_TRANSFER_IM_BANK';
export const DERIVATIVES_TRANSFER_QUERY_TRANSFER_IM_FEE = 'DERIVATIVES_TRANSFER_QUERY_TRANSFER_IM_FEE';
export const DERIVATIVES_TRANSFER_QUERY_TRANSFER_IM_HISTORY = 'DERIVATIVES_TRANSFER_QUERY_TRANSFER_IM_HISTORY';
export const DERIVATIVES_TRANSFER_QUERY_WITHDRAW_IM_INFO = 'DERIVATIVES_TRANSFER_QUERY_WITHDRAW_IM_INFO';
export const DERIVATIVES_TRANSFER_WITHDRAW_IM_REQUEST = 'DERIVATIVES_TRANSFER_WITHDRAW_IM_REQUEST';

export const SPEED_ORDER_PLACE_ORDER = 'SPEED_ORDER_PLACE_ORDER';
export const SPEED_ORDER_MODIFY_ORDER = 'SPEED_ORDER_MODIFY_ORDER';
export const SPEED_ORDER_CANCEL_ORDER = 'SPEED_ORDER_CANCEL_ORDER';
export const SPEED_ORDER_MOVE_ORDER = 'SPEED_ORDER_MOVE_ORDER';
export const SPEED_ORDER_PLACE_DERIVATIVES_ORDER = 'SPEED_ORDER_PLACE_DERIVATIVES_ORDER';
export const SPEED_ORDER_CANCEL_DERIVATIVES_ORDER = 'SPEED_ORDER_CANCEL_DERIVATIVES_ORDER';
export const SPEED_ORDER_MOVE_DERIVATIVES_ORDER = 'SPEED_ORDER_MOVE_DERIVATIVES_ORDER';

export const REGISTER_ACCOUNT_FORM = 'REGISTER_ACCOUNT_FORM';
export const RESEND_REGISTER_ACCOUNT_OTP = 'RESEND_REGISTER_ACCOUNT_OTP';
export const SEND_ID_IMAGE = 'SEND_ID_IMAGE';
export const REGISTER_ACCOUNT_CONFIRM_OTP = 'REGISTER_ACCOUNT_CONFIRM_OTP';
export const GET_FACE_ACTION = 'GET_FACE_ACTION';
export const SEND_FACE_IMAGES = 'SEND_FACE_IMAGES';
export const QUERY_BANK_LIST = 'QUERY_BANK_LIST';
export const QUERY_BANK_BRANCH = 'QUERY_BANK_BRANCH';
export const FINISH_REGISTER_ACCOUNT = 'FINISH_REGISTER_ACCOUNT';
export const CHECK_REFERRAL_CODE = 'CHECK_REFERRAL_CODE';
export const SEND_NEED_SUPPORT = 'SEND_NEED_SUPPORT';

export const OPEN_BANK_ACCOUNT = 'OPEN_BANK_ACCOUNT';
export const TOGGLE_BANNER = 'TOGGLE_BANNER';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const CHECK_ID = 'CHECK_ID';

export const QUERY_CASH_IN_ADVANCE = 'QUERY_CASH_IN_ADVANCE';
export const SUBMIT_ADVANCE_PAYMENT_CREATION = 'SUBMIT_ADVANCE_PAYMENT_CREATION';
export const CHECK_TIME_SUBMIT_ADVANCE_PAYMENT = 'CHECK_TIME_SUBMIT_ADVANCE_PAYMENT';
export const QUERY_TRANSACTION_INFO = 'QUERY_TRANSACTION_INFO';
export const QUERY_CALCULATE_INTEREST = 'QUERY_CALCULATE_INTEREST';

export const QUERY_PORTFOLIO_LIST = 'QUERY_PORTFOLIO_LIST';
export const QUERY_CLIENT_CASH_BALANCE = 'QUERY_CLIENT_CASH_BALANCE';

export const QUERY_POSITION_STATEMENT = 'QUERY_POSITION_STATEMENT';

export const QUERY_CASH_STATEMENT = 'QUERY_CASH_STATEMENT';
export const DERIVATIVES_ACCOUNT_QUERY_CASH_BALANCE = 'DERIVATIVES_ACCOUNT_QUERY_CASH_BALANCE';

export const QUERY_BANK_INFO_IICA = 'QUERY_BANK_INFO_IICA';

export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const COMFIRM_ACCOUNT_NO = 'COMFIRM_ACCOUNT_NO';

export const MARKET_FOLLOW_SYMBOL_REFRESH = 'market/MARKET_FOLLOW_REFRESH';
